# Small local network of three nodes using the fastest mean15
version: '3'
services:

  bitcoin1:
    build: ../bitcoin
    cap_add:
      - ALL
    command: bitcoind -addnode=10.7.0.12:12345 -addnode=10.7.0.13:12345 --wallet=skunk -port=12345
    volumes: 
     - ${PWD}/bitcoin1:/root/.bitcoin
     - ${PWD}/wallets:/root/.bitcoin/wallets
     - ${PWD}/bitcoin.conf:/root/.bitcoin/bitcoin.conf
    networks:
      vpcbr:
        ipv4_address: 10.7.0.11

  bitcoin2:
    build: ../bitcoin
    cap_add:
      - ALL
    command: bitcoind -addnode=10.7.0.11:12345 -addnode=10.7.0.13:12345 --wallet=skunk -port=12345
    volumes:
     - ${PWD}/bitcoin2:/root/.bitcoin
     - ${PWD}/wallets:/root/.bitcoin/wallets
     - ${PWD}/bitcoin.conf:/root/.bitcoin/bitcoin.conf
    networks:
      vpcbr:
        ipv4_address: 10.7.0.12

  bitcoin3:
    build: ../bitcoin
    cap_add:
      - ALL
    command: bitcoind -addnode=10.7.0.12:12345 -addnode=10.7.0.11:12345 --wallet=skunk -port=12345
    volumes:
     - ${PWD}/bitcoin3:/root
     - ${PWD}/wallets:/root/wallets
     - ${PWD}/bitcoin.conf:/root/.bitcoin/bitcoin.conf
    networks:
      vpcbr:
        ipv4_address: 10.7.0.13

  kyiv:
    build: ../aeternity
    hostname: kyiv
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ${PWD}/node/config/kyiv.yaml:/home/aeternity/aeternity.yaml
      - ${PWD}/node/keys/kyiv:/home/aeternity/node/keys
        # - kyiv_db:/home/aeternity/node/data/mnesia
    depends_on:
      - bitcoin1
    networks:
      vpcbr:
        ipv4_address: 10.7.0.15

  proxy:
    image: nginx:1.13.8
    hostname: proxy
    ports:
     - "3001:3001"
     - "3002:3002"
     - "3003:3003"
    volumes:
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/nginx/cors.conf:/etc/nginx/cors.conf
      - ${PWD}/nginx/ws.conf:/etc/nginx/ws.conf

volumes:
  kyiv_db:
  krakow_db:
  munich_db:

networks:
  vpcbr:
   driver: bridge
   ipam:
     config:
      - subnet: 10.7.0.0/16
       
        
