# Small local network of three nodes using the fastest mean15
version: '3'
services:

  bitcoin:
    build: ./bitcoin
    cap_add:
      - ALL
    command: bitcoind -addnode=10.7.0.12:12345 -addnode=10.7.0.13:12345 --wallet=skunk -port=12345
    volumes:
     - ./bitcoin1:/root/.bitcoin
     - ./wallets:/root/.bitcoin/wallets
     - ./bitcoin/bitcoinf.conf:/root/.bitcoin/bitcoin.conf
    networks:
      vpcbr:
        ipv4_address: 10.7.0.11

  krakow:
    build: ./aeternity
    hostname: krakow
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ./node/config/krakow.yaml:/home/aeternity/aeternity.yaml
      - ./node/krakow/krakow:/home/aeternity/node/keys
    depends_on:
      - bitcoin
    networks:
      vpcbr:
        ipv4_address: 10.7.0.15

  kyiv:
    build: ./aeternity
    hostname: kyiv
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ./node/config/kyiv.yaml:/home/aeternity/aeternity.yaml
      - ./node/keys/kyiv:/home/aeternity/node/keys
    depends_on:
      - bitcoin
    networks:
      vpcbr:
        ipv4_address: 10.7.0.16

  munich:
    build: ./aeternity
    hostname: munich
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ./node/config/munich.yaml:/home/aeternity/aeternity.yaml
      - ./node/keys/munich:/home/aeternity/node/keys
    depends_on:
      - bitcoin
    networks:
      vpcbr:
        ipv4_address: 10.7.0.17

volumes:
  kyiv_db:
  krakow_db:
  munich_db:

networks:
  vpcbr:
   driver: bridge
   ipam:
     config:
      - subnet: 10.7.0.0/16
