# Small local network of three nodes using the fastest mean15
version: '3'
services:

  bitcoin:
    build: bitcoin
    cap_add:
      - ALL
    command: bitcoind -addnode=10.7.0.12:12345 -addnode=10.7.0.13:12345 --wallet=skunk -port=12345
    volumes:
     - ${PWD}/bitcoin:/root/.bitcoin
     - ${PWD}/wallets:/root/.bitcoin/wallets
     - ${PWD}/config/bitcoin/bitcoin.conf:/root/.bitcoin/bitcoin.conf
    networks:
      vpcbr:
        ipv4_address: 10.7.0.11

  kyiv:
    build: aeternity
    hostname: kyiv
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ${PWD}/config/aeternity/kyiv.yaml:/home/aeternity/aeternity.yaml
      - kyiv_db:/home/aeternity/node/data/mnesia
    depends_on:
      - bitcoin
    networks:
      vpcbr:
        ipv4_address: 10.7.0.12

  krakow:
    build: aeternity
    hostname: krakow
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ${PWD}/config/aeternity/krakow.yaml:/home/aeternity/aeternity.yaml
      - krakow_db:/home/aeternity/node/data/mnesia
    depends_on:
      - bitcoin
    networks:
      vpcbr:
        ipv4_address: 10.7.0.13

  munich:
    build: aeternity
    hostname: munich
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ${PWD}/config/aeternity/munich.yaml:/home/aeternity/aeternity.yaml
      - munich_db:/home/aeternity/node/data/mnesia
    depends_on:
      - bitcoin
    networks:
      vpcbr:
        ipv4_address: 10.7.0.14

volumes:
  kyiv_db:
  krakow_db:
  munich_db:

networks:
  vpcbr:
   driver: bridge
   ipam:
     config:
      - subnet: 10.7.0.0/16
