# Small local network of three nodes using the fastest mean15
version: '3'
services:

  bitcoin:
    build:
      context: https://github.com/aeternity/aeternity/tree/hyperchains-playground
    cap_add:
      - ALL
    command: bitcoind -wallet=skunk
    volumes:
     - ${PWD}/bitcoin:/root/.bitcoin
     - ${PWD}/config/bitcoin/bitcoin.conf:/root/.bitcoin/bitcoin.conf
    networks:
      vpcbr:
        ipv4_address: 10.7.0.11

  kyiv:
    build:
      context: https://github.com/aeternity/aeternity/tree/hyperchains-playground
    hostname: kyiv
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ${PWD}/config/aeternity/kyiv.yaml:/home/aeternity/aeternity.yaml
      - kyiv_db:/home/aeternity/node/data/mnesia
    depends_on:
      - bitcoin
    networks:
      vpcbr:
        ipv4_address: 10.7.0.12

  krakow:
    build:
      context: https://github.com/aeternity/aeternity/tree/hyperchains-playground
    hostname: krakow
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ${PWD}/config/aeternity/krakow.yaml:/home/aeternity/aeternity.yaml
      - krakow_db:/home/aeternity/node/data/mnesia
    depends_on:
      - bitcoin
    networks:
      vpcbr:
        ipv4_address: 10.7.0.13

  tehran:
    build: aeternity
    hostname: tehran
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ${PWD}/config/aeternity/tehran.yaml:/home/aeternity/aeternity.yaml
      - tehran_db:/home/aeternity/node/data/mnesia
    depends_on:
      - bitcoin
    networks:
      vpcbr:
        ipv4_address: 10.7.0.14

volumes:
  kyiv_db:
  krakow_db:
  tehran_db:

networks:
  vpcbr:
   driver: bridge
   ipam:
     config:
      - subnet: 10.7.0.0/16
