# Small local network of three nodes using the fastest mean15
version: '3'
services:

  bitcoin:
    build: bitcoin
    cap_add:
      - ALL
    command: bitcoind -wallet=hyperchains
    volumes:
     - ./config/bitcoin/bitcoin.conf:/root/.bitcoin/bitcoin.conf
    networks:
      vpcbr:
        ipv4_address: 10.7.0.11

  kyiv:
    build:
      context: https://github.com/aeternity/aeternity.git#hyperchains-playground
    hostname: kyiv
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ./config/aeternity/kyiv.yaml:/home/aeternity/aeternity.yaml
    depends_on:
      - bitcoin
    networks:
      vpcbr:
        ipv4_address: 10.7.0.12

  krakow:
    build:
      context: https://github.com/aeternity/aeternity.git#hyperchains-playground
    hostname: krakow
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ./config/aeternity/krakow.yaml:/home/aeternity/aeternity.yaml
    depends_on:
      - bitcoin
    networks:
      vpcbr:
        ipv4_address: 10.7.0.13

  munich:
    build:
      context: https://github.com/aeternity/aeternity.git#hyperchains-playground
    hostname: munich
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: >
      bin/aeternity console -noinput -aecore expected_mine_rate ${AETERNITY_MINE_RATE:-15000}
    volumes:
      - ./config/aeternity/munich.yaml:/home/aeternity/aeternity.yaml
    depends_on:
      - bitcoin
    networks:
      vpcbr:
        ipv4_address: 10.7.0.14

networks:
  vpcbr:
   driver: bridge
   ipam:
     config:
      - subnet: 10.7.0.0/16
