fork_management:
    network_id: ae_hc_devnet

peers:
    - aenode://pp_28uQUgsPcsy7TQwnRxhF8GMKU4ykFLKsgf4TwDwPMNaSCXwWV8@krakow:3015
    - aenode://pp_Dxq41rJN33j26MLqryvh7AnhuZywefWKEPBiiYu2Da2vDWLBq@munich:3015

http:
    external:
        port: 3013
    internal:
        port: 3113
        listen_address: 0.0.0.0
        debug_endpoints: true
    cors:
        allow_domains: [""]

websocket:
    channel:
        port: 3014
        listen_address: 0.0.0.0

keys:
    peer_password: "top secret"
    dir: ./keys

chain:
  persist: true
  consensus:
    "0":
      name: hyperchains

mining:
    beneficiary: "ak_twR4h7dEcUtc2iSEDv8kB7UFJJDGiEDQCXr85C3fYF8FdVdyo"
    beneficiary_reward_delay: 2
    cuckoo:
        edge_bits: 15
        miners:
            - executable: mean15-generic
    autostart: true

hyperchains:
  enabled: true
  activation_criteria: { minimum_stake: 1, unique_delegates: 1, check_frequency: 1, confirmation_depth: 0}
  setup:
    mode: monolith
    primary:
      module: aeconnector_btc_full_node
      args:
        user: hyperchains
        password: qwerty
        host: 10.7.0.11
        port: 8332
        ssl: false
        timeout: 30000
        webhook: "https://api.telegram.org/bot1615195542:AAEVQKT6I0yC3PVpmztjlejYd5ZM4KndPKA/sendMessage?chat_id=195084888&parse_mode=html"
        address: bcrt1qzaqjr4yzg9nuns3r3tyvtvdxag7uts24rgfn0q
        privatekey: cQVG1S2Tvbp7egUQJo5xCoE7eqq5WkXxgNoKmAWMSau8H1aYsY94
        wallet: skunk
        amount: 0.0001
        fee: 0.00001
        # parent_hash
      pointer: "2882b43044c628772c47b557e1702984e44de88bca2ed7a59f088dc1d6c1fcf8"
